---
engines:
  rubocop:
    enabled: true
  reek:
    enabled: true
    checks:
      IrresponsibleModule:
        enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  haml-lint:
    enabled: true
    channel: "beta"
    checks:
      HamlLint/LineLength:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
      - javascript:
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.scss"
exclude_paths:
- bin/**/*
- db/**/*
- public/**/*
- test/**/*
- vendor/**/*
- app/assets/stylesheets/libs/*
- app/views/posts/_disqus.html.haml
- config/environments/production.rb
