---
engines:
  rubocop:
    enabled: true
  reek:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  haml-lint:
    enabled: true
    channel: "beta"
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
      - javascript:
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.scss"
exclude_paths:
- test/**/*
- "**/vendor/**/*"
